### ISSUE TITLE
Expo

### ISSUE THREAD

**Issue by igbcampos** [WrathChaos/react-native-duo-toggle-switch#1]
I'm not able to use this library with expo because of a dependency (react-native-androw), do you know how to fix this?

**Comment by WrathChaos** [comment]
Hello @igbcampos ,
If you want I can extract the androw and create the expo branch. However, without androw, Android's shadow is not working well. Do you want it anyway?

**Comment by A-Rodriguez-Monge** [comment]
Hi! I'm wondering how I can install the expo branch so that I can go around the androw dependency

**Comment by WrathChaos** [comment]
Hello @A-Rodriguez-Monge,

I can remove androw dependency once and for all. Since anyone can wrap the androw or something like that as a wrapper.
It will be available today

**Comment by WrathChaos** [comment]
Hello again @A-Rodriguez-Monge 
I've updated the whole library with Typescript and some new stuff. 

WARNING! There are some breaking changes. Please take a look at the documentation for the new usage. 

Please try 1.0.1 and also I updated the example with an expo one :)

**Comment by A-Rodriguez-Monge** [comment]
What a legend. I'll try this out soon. Thanks for the quick response and action!
