### ISSUE TITLE
Im crying because of joy;)))))

### ISSUE THREAD

**Issue by SurpriseMF3000** [WrathChaos/react-native-duo-toggle-switch#148]
Thank you for this Repository and Packet;)
A packet that's just working and exactly doing what you want it to do with just 5 lines of code is AMAZING!!!

No building or dependency errors!
Great documentation!
All possibilities!

Sounds weird but this is so satisfying;)

**Comment by WrathChaos** [comment]
Hello @SurpriseMF3000 
Thank you so much for these kind words :) 

I just upgraded the example, if you have any ideas to improve the library please share with me :) 

Thank you again!
