### ISSUE TITLE
How to add padding to button/text?

### ISSUE THREAD

**Issue by thecompoundingdev** [WrathChaos/react-native-duo-toggle-switch#70]
When my text is longer than 7 characters it gets cut off. I need to add padding and make the component wider but adding padding or margin via `primaryTextStyle `or `secondaryTextStyle` results in text wrapping. 

I suppose we need a prop that lets us edit the  text container's style

Here's my current component:
![Screen Shot 2022-06-23 at 8 42 41 AM](https://user-images.githubusercontent.com/39289298/175301032-96df89ff-9f16-494d-88b5-f0c6db738f60.png)
.
After trying to add some room with padding or margin on text:
`        primaryTextStyle={{ marginHorizontal: 10 }}
`
![Screen Shot 2022-06-23 at 8 45 33 AM](https://user-images.githubusercontent.com/39289298/175301645-6c57ca92-209c-442a-9758-ff6561346b0d.png)

**Comment by WrathChaos** [comment]
Hello @thecompoundingdev 

[Version 1.1.0](https://github.com/WrathChaos/react-native-duo-toggle-switch/releases/tag/1.1.0)  is available with two new props: `primaryButtonStyle` and `secondaryButtonStyle`.

Here is the example usage:

```jsx
<DuoToggleSwitch
          primaryText="Customers"
          secondaryText="Employees"
          onPrimaryPress={() => {}}
          onSecondaryPress={() => {}}
          TouchableComponent={Ripple}
          primaryButtonStyle={{ width: 150 }}
          secondaryButtonStyle={{ width: 125 }}
          primaryTextStyle={{ marginRight: 32 }}
          rippleColor="#fff"
          rippleContainerBorderRadius={50}
/>
```

You can customize it for your use-case :)

**Comment by thecompoundingdev** [comment]
Thanks, it seems like the primaryButtonStyle may be improperly attributed, however. I set margin on both but it's only working on second button.
<img width="192" alt="Screen Shot 2022-07-04 at 11 41 47 AM" src="https://user-images.githubusercontent.com/39289298/177186272-8d18ac99-2892-42a1-a22a-2669347189d4.png">
!
`primaryButtonStyle={{
          flexDirection: 'row',
          alignItems: 'center',
          marginHorizontal: 50,
        }}
        secondaryButtonStyle={{
          flexDirection: 'row',
          alignItems: 'center',
          marginHorizontal: 50,
        }}`

Additionally, flex alignment doesn't work.

**Comment by WrathChaos** [comment]
Why are putting the flexDirection row for these? Try to set with `width` instead of `marginHorizontal`. Please check out the `example`
